export default [
  {
    id: "35577308923",
    width: 512,
    height: 640,
    source: require("../../../assets/panel2/d.jpg"),
    filter: "drop",
  },
  {
    id: "36390435575",
    postedBy: "Dylan Toh",
    width: 640,
    height: 427,
    title: "Ghost Express",
    source: require("../../../assets/panel2/line1.jpg"),
    filter: "line_1",
  },
  {
    id: "36221070302",
    postedBy: "Wim Boon",
    width: 640,
    height: 380,
    title: "Heideblauwtje - Silver-studded blue",
    source: require("../../../assets/panel2/overlay1.jpg"),
    filter: "overlay",
  },
  {
    id: "36334926986",
    postedBy: "dizbin",
    width: 512,
    height: 640,
    title: "white light",
    source: require("../../../assets/panel2/splatter3.jpg"),
    filter: "splatter_2",
  },
  {
    id: "36219754712",
    postedBy: "ThorstenKoch",
    width: 640,
    height: 402,
    title: "to fast",
    source: require("../../../assets/panel2/text.jpg"),
    filter: "text",
  },
  {
    id: "36378437285",
    postedBy: "Willa Wei",
    width: 640,
    height: 427,
    title: "Bountiful Glory",
    source: require("../../../assets/panel2/d1.jpg"),
    filter: "drop_1",
  },
  {
    id: "36385293895",
    postedBy: "Manfred Hartmann",
    width: 640,
    height: 360,
    title: "clouds",
    source: require("../../../assets/panel2/exp2.jpg"),
    filter: "exp_2",
  },
  {
    id: "35981101570",
    postedBy: "Eric Isley",
    width: 640,
    height: 426,
    title: "Eastern Ringtail",
    source: require("../../../assets/panel2/line2.jpg"),
    filter: "line_2",
  },
  {
    id: "36215026892",
    postedBy: "marcel bakker",
    width: 640,
    height: 480,
    title: "Fear of heights?",
    source: require("../../../assets/panel2/mirror.jpg"),
    filter: "mirror",
  },
  {
    id: "36383381609",
    postedBy: "Gerhard R.",
    width: 640,
    height: 421,
    title: "Kreiskunst",
    source: require("../../../assets/panel2/overlay2.jpg"),
    filter: "overlay_2",
  },
  {
    id: "36383381605",
    postedBy: "Gerhard R.",
    width: 640,
    height: 421,
    title: "Kreiskunst",
    source: require("../../../assets/panel2/splatter2.jpg"),
    filter: "splatter_1",
  },
  {
    id: "36342182536",
    postedBy: "Malen Garek",
    width: 640,
    height: 640,
    title: "I'm in holidays! (iPhone Shot)",
    source: require("../../../assets/panel2/d2.jpg"),
    filter: "drop_2",
  },
  {
    id: "36254546171",
    postedBy: "John Assheton",
    width: 640,
    height: 640,
    title: "Ruddy Darter (M)",
    source: require("../../../assets/panel2/exp1.jpg"),
    filter: "exp_1",
  },
  {
    id: "35580273200",
    width: 640,
    height: 640,
    source: require("../../../assets/panel2/splatter1.jpg"),
    filter: "splatter",
  },
];
